# Generated by Django 5.1.5 on 2025-02-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_alter_users_options_alter_users_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
