# Generated by Django 5.1.5 on 2025-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0009_passwordreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="user",
            field=models.EmailField(max_length=254),
        ),
    ]
