# Generated by Django 5.1.5 on 2025-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0010_alter_passwordreset_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="favouriteitems",
            name="direction_of_like",
            field=models.IntegerField(default=0),
        ),
    ]
