# Generated by Django 5.1.5 on 2025-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0011_delete_product_favouriteitems_direction_of_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="post_city",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="orders",
            name="post_departament",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="orders",
            name="user_number",
            field=models.IntegerField(default=0),
        ),
    ]
