name: Deploy Django to AWS

on:
  push:
    branches:
      - main  # Запускать деплой при коммитах в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      env:
        AWS_REGION: us-east-1  
        AWS_ACCOUNT_ID: 615299773884  
        IMAGE_NAME: pet-shop
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

    - name: Deploy to AWS ECS
      env:
        CLUSTER_NAME: pet-shop-cluster
        SERVICE_NAME: pet-shop-service
        AWS_REGION: us-east-1
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
